### ISSUE TITLE
TODO + ideas for rewrite

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Magic-Spoiler#229]
**TODO**
- [x] drop sets which have `card_count: 0`, like M20 (https://api.scryfall.com/sets/m20)
- [x] output files are no longer pretty printed with spaces/tabs ([spoiler.xml](https://github.com/Cockatrice/Magic-Spoiler/blob/files/spoiler.xml), [WAR.xml](https://github.com/Cockatrice/Magic-Spoiler/blob/files/WAR.xml), [MH1.xml](https://github.com/Cockatrice/Magic-Spoiler/blob/files/MH1.xml) ...)
- [x] delete other scraper files as it's scryfall only now
([scryfall_scraper.py](https://github.com/Cockatrice/Magic-Spoiler/blob/master/scryfall_scraper.py) is unused now too, and main.py contains everything needed?)
- [x] ~~spoiler xml files use `"` while Cockatrice's cards.xml uses `'` in the meta data~~
- [x] Only creates .xml, .json...
xml got added here: https://github.com/Cockatrice/Magic-Spoiler/commit/31fbc265bc7560b0984be2798ed5cf5bf799af89 (but not the json)

<br>

**IDEA**
- [x] `long name`, `set type`, `release date` could all come from the scryfall api as well instead manual maintaining those in the [set_info.yml](https://github.com/Cockatrice/Magic-Spoiler/blob/master/set_info.yml) file
- [x] we don't need to use the set_info file at all, and could automatically detect new sets on scryfall via the api (https://api.scryfall.com/sets)
e.g. cache the list with set code and date and check for changes, or in case it's ordered (it looks to be by release date?) check last 10 entries and add new ones (only with cards>0 and release date in the future)
but we would want to filter out tokens (tWAR, "War of the Spark Tokens"), promos (pWAR, "War of the Spark Promos") and maybe others... (maybe by set_type?)
- [x] automatically drop sets with release date in the past or today
- [x] cleanup old spoiled files (from files branch) which are released, too!
(e.g. rna.json, rna.xml when they get removed from spoiler xml because of their release date)
- [x] date got updated, even though there was no change in this file: https://github.com/Cockatrice/Magic-Spoiler/commit/c4f23ece1c269dc4093051c8fbbe1eccb0a3219c#diff-ec52870eab224ec8d115eaa970355db6R4
We want to check on a per file basis

**Comment by tooomm** [comment]
Some more:
- [ ] All json files have no data for sets and booster anymore
At least the set information should be there, in case scryfall has no booster info.
Changing commit: https://github.com/Cockatrice/Magic-Spoiler/commit/1a7f698e588be0c2c7047be7f9777ed54e7091e1
Result in file: https://github.com/Cockatrice/Magic-Spoiler/commit/a51a771fdeede89e7b222f1f872b5aa5d5ee7b01#diff-48329b3280f748b924fb50e19d5a2127
I thought the json file got build as basis and the xml used to be derived from that?
- [x] Update main readme with requirements and instructions
- [x] Automate SpoilerSeasonEnabled file creation + deletion
Create when spoiler.xml contains a set, remove when there are no sets left to control that Cockatrice only pulls the spoiler file when actually needed.

**Comment by ZeldaZach** [comment]
I don't have further intentions to modify the program at this point, so don't expect anything more for the time being. I solved the issues that were going on and moved it to a more stable source. This project is open for external explorations.
